### ISSUE TITLE
How run command convert to docker-compose?

### ISSUE THREAD

**Issue by nikanet** [cilix-lab/docker-netatalk#2]
Hi!
Nice work! I'm using docker-compose for automate start all containers. Please tell how translate your RUN command in docker-compose.yml file?

For example:
docker run -it -p 548:548 -v "/home/myuser:/shares/documents" cilix/netatalk -p -u "myuser;mypass" -s "Documents;/shares/documents;nobody;myuser;yes"

**Comment by cilix-lab** [comment]
I'm no longer maintaining this repository. You could translate that into something like:

```
version: "2"
services:
  mqtt:
    image: cilix/netatalk
    container_name: netatalk
    restart: always
    ports:
      - 548:548
    volumes:
      - "/home/myuser:/shares/documents"
    command: -p -u "myuser;mypass" -s "Documents;/shares/documents;nobody;myuser;yes"
```
